[phases.setup]
nixPkgs = ["nodejs-20.x"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["npm run build"]

#[phases.test] 
#cmds = ["npm test"]

[start]
cmd = "npm run start"
